[build]
  command = "npm run generate"
  functions = "netlify/"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/GAMWxmR"
  status = 301
  force = true

[[redirects]]
  from = "/telegram"
  to = "https://t.me/hoppscotch"
  status = 301
  force = true

[[redirects]]
  from = "/beta"
  to = "https://forms.gle/XPYDMp8m6JHNWcYp9"
  status = 301
  force = true
