[build]
  base = "/"
  publish = "packages/hoppscotch-app/dist"
  command = "pnpm run generate"
  environment = { NODE_VERSION = "14" }

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/GAMWxmR"
  status = 301
  force = true

[[redirects]]
  from = "/telegram"
  to = "https://t.me/hoppscotch"
  status = 301
  force = true

[[redirects]]
  from = "/beta"
  to = "https://forms.gle/XPYDMp8m6JHNWcYp9"
  status = 301
  force = true

[[redirects]]
  from = "/careers"
  to = "https://www.notion.so/hoppscotch/3b9d5d5239a043bfb91701faabf5b8f0"
  status = 301
  force = true

[[redirects]]
  from = "/newsletter"
  to = "http://eepurl.com/hy0eWH"
  status = 301
  force = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/hoppscotch_io"
  status = 301
  force = true
